name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
   techread_showcase:
     path: ../
   flutter:
    sdk: flutter
   widgetbook: ^3.18.0
   widgetbook_annotation: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.18.0
  build_runner: ^2.10.0

flutter:
  uses-material-design: true
